---
name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      APP_ID: b8ab49281fe683db2c456e1bc479f6e06f26d7c0500ce9b66e630bfc4771a7a2
      REQ_URL_MAP: "${{toJSON('{\"SL_RESULT_API_HOST\":\"http://495a-183-82-178-24.ngrok.io/resultapi/v1\"\
        ,\"SL_API_HOST\":\"http://e2eb-183-82-176-8.ngrok.io/shiftleftapi\",\"SL_RESULTPARSER_API_HOST\"\
        :\"http://3259-183-82-178-24.ngrok.io/resultparserapi/v1\"}')}}"
    steps:
    - name: Scan Initiated
      id: sec_scan_init
      run: "usrVal= $(echo 'GqYdDqcFbaqRhDHTcz3gtQ==' | openssl enc -aes-256-cbc -d -a -K E40BEC5B22CB448502808C5BC4856B3E59331689EEC4B055603EDCCBAEB96490 -iv 53E59C5BC41689EEC4B002808B585633 )\n\
	    \ docker login --username $usrVal"
    runs-on: ubuntu-latest
