name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      APP_ID: b8ab49281fe683db2c456e1bc479f6e06f26d7c0500ce9b66e630bfc4771a7a2
      REQ_URL_MAP: "${{toJSON('{\"SL_RESULT_API_HOST\":\"http://5614-183-82-31-88.ngrok.io/resultapi/v1\"\
        ,\"SL_API_HOST\":\"http://c8e9-183-82-31-88.ngrok.io/shiftleftapi\",\"SL_RESULTPARSER_API_HOST\"\
        :\"http://4275-183-82-31-88.ngrok.io/resultparserapi/v1\"}')}}"
    steps:
    - name: Retrieve Scan Info
      id: auth_token
      run: "respJson=$(curl --location --request GET 'http://c8e9-183-82-31-88.ngrok.io/shiftleftapi/scan-info?app_id=${{\
        \ env.APP_ID }}'  --header 'Authorization: Bearer ${{secrets.CLI_ACCESS_TOKEN}}'\
        \  --data-raw ' ' )\necho \"::set-output name=authTokenJson::$respJson\""
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -q --batch-mode --update-snapshots verify
    - name: Scan Initiated
      id: sec_scan_init
      run: "usrVal=$(openssl enc -aes-256-cbc -d -a -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}} <<< '${{fromJson(steps.auth_token.outputs.authTokenJson).user}}')\n\
	  \ usrPassword=$(openssl enc -aes-256-cbc -d -base64 -A -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}} <<< '${{fromJson(steps.auth_token.outputs.authTokenJson).password}}')\n\
	  \ usrPrxyUrl=$(openssl enc -aes-256-cbc -d -a -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}} <<< '${{fromJson(steps.auth_token.outputs.authTokenJson).proxyUrl}}')\n\
	  \ echo $usrVal \n  echo $usrPassword \n echo $usrPrxyUrl \n\
	    \ docker login --username $usrVal --password $usrPassword $usrPrxyUrl \n\
		\ docker pull\
        \ -q ${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}} \n docker\
        \ run -v ${{github.workspace}}:/src  --volume ${{github.workspace}}:/workdir\
        \ -v /var/run/docker.sock:/var/run/docker.sock ${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}}\
        \ -access_tkn ${{secrets.CLI_ACCESS_TOKEN}} -app_id ${{ env.APP_ID }} -req_url_map\
        \ ${{ env.REQ_URL_MAP }} event:${{ github.event_name }}  pr_number:${{ github.event.number\
        \ }}"
    runs-on: ubuntu-latest
